// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feed_follow.sql

package database

import (
	"context"
	"database/sql"
)

const createFeedFollow = `-- name: CreateFeedFollow :exec
INSERT INTO feed_follow(created_at, updated_at, user_id, feed_id)
VALUES (
    $1, $2, $3, $4
)
`

type CreateFeedFollowParams struct {
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	UserID    int32
	FeedID    int32
}

func (q *Queries) CreateFeedFollow(ctx context.Context, arg CreateFeedFollowParams) error {
	_, err := q.db.ExecContext(ctx, createFeedFollow,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.FeedID,
	)
	return err
}

const deleteRelation = `-- name: DeleteRelation :exec
DELETE FROM feed_follow WHERE ((user_id = $1) AND (feed_id = $2))
`

type DeleteRelationParams struct {
	UserID int32
	FeedID int32
}

func (q *Queries) DeleteRelation(ctx context.Context, arg DeleteRelationParams) error {
	_, err := q.db.ExecContext(ctx, deleteRelation, arg.UserID, arg.FeedID)
	return err
}

const getFeedByUser = `-- name: GetFeedByUser :many
SELECT feed_id FROM feed_follow WHERE user_id = $1
`

func (q *Queries) GetFeedByUser(ctx context.Context, userID int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getFeedByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var feed_id int32
		if err := rows.Scan(&feed_id); err != nil {
			return nil, err
		}
		items = append(items, feed_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeedsByFeed = `-- name: GetFeedsByFeed :many
SELECT id, created_at, updated_at, user_id, feed_id FROM feed_follow
WHERE feed_id = $1
`

func (q *Queries) GetFeedsByFeed(ctx context.Context, feedID int32) ([]FeedFollow, error) {
	rows, err := q.db.QueryContext(ctx, getFeedsByFeed, feedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FeedFollow
	for rows.Next() {
		var i FeedFollow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.FeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeedsByUser = `-- name: GetFeedsByUser :many
SELECT id, created_at, updated_at, user_id, feed_id FROM feed_follow
WHERE user_id = $1
`

func (q *Queries) GetFeedsByUser(ctx context.Context, userID int32) ([]FeedFollow, error) {
	rows, err := q.db.QueryContext(ctx, getFeedsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FeedFollow
	for rows.Next() {
		var i FeedFollow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.FeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersByFeed = `-- name: GetUsersByFeed :many
SELECT user_id FROM feed_follow WHERE feed_id = $1
`

func (q *Queries) GetUsersByFeed(ctx context.Context, feedID int32) ([]int32, error) {
	rows, err := q.db.QueryContext(ctx, getUsersByFeed, feedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var user_id int32
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
