// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feeds.sql

package database

import (
	"context"
)

const createFeed = `-- name: CreateFeed :exec
INSERT INTO feeds(user_id, name, url)
VALUES(
    $1,
    $2,
    $3
)
`

type CreateFeedParams struct {
	UserID int32
	Name   string
	Url    string
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) error {
	_, err := q.db.ExecContext(ctx, createFeed, arg.UserID, arg.Name, arg.Url)
	return err
}
